// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/records_grpc.pb.go

// Package server is a generated GoMock package.
package server

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockRecordsClient is a mock of RecordsClient interface.
type MockRecordsClient struct {
	ctrl     *gomock.Controller
	recorder *MockRecordsClientMockRecorder
}

// MockRecordsClientMockRecorder is the mock recorder for MockRecordsClient.
type MockRecordsClientMockRecorder struct {
	mock *MockRecordsClient
}

// NewMockRecordsClient creates a new mock instance.
func NewMockRecordsClient(ctrl *gomock.Controller) *MockRecordsClient {
	mock := &MockRecordsClient{ctrl: ctrl}
	mock.recorder = &MockRecordsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordsClient) EXPECT() *MockRecordsClientMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockRecordsClient) Add(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Add", varargs...)
	ret0, _ := ret[0].(*AddRecordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockRecordsClientMockRecorder) Add(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockRecordsClient)(nil).Add), varargs...)
}

// Delete mocks base method.
func (m *MockRecordsClient) Delete(ctx context.Context, in *DeleteRecordRequest, opts ...grpc.CallOption) (*DeleteRecordResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*DeleteRecordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockRecordsClientMockRecorder) Delete(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRecordsClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockRecordsClient) Get(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*GetRecordResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*GetRecordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRecordsClientMockRecorder) Get(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRecordsClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockRecordsClient) List(ctx context.Context, in *ListRecordRequest, opts ...grpc.CallOption) (*ListRecordResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*ListRecordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRecordsClientMockRecorder) List(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRecordsClient)(nil).List), varargs...)
}

// Update mocks base method.
func (m *MockRecordsClient) Update(ctx context.Context, in *UpdateRecordRequest, opts ...grpc.CallOption) (*UpdateRecordResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*UpdateRecordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRecordsClientMockRecorder) Update(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRecordsClient)(nil).Update), varargs...)
}

// MockRecordsServer is a mock of RecordsServer interface.
type MockRecordsServer struct {
	ctrl     *gomock.Controller
	recorder *MockRecordsServerMockRecorder
}

// MockRecordsServerMockRecorder is the mock recorder for MockRecordsServer.
type MockRecordsServerMockRecorder struct {
	mock *MockRecordsServer
}

// NewMockRecordsServer creates a new mock instance.
func NewMockRecordsServer(ctrl *gomock.Controller) *MockRecordsServer {
	mock := &MockRecordsServer{ctrl: ctrl}
	mock.recorder = &MockRecordsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordsServer) EXPECT() *MockRecordsServerMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockRecordsServer) Add(arg0 context.Context, arg1 *AddRecordRequest) (*AddRecordResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0, arg1)
	ret0, _ := ret[0].(*AddRecordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockRecordsServerMockRecorder) Add(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockRecordsServer)(nil).Add), arg0, arg1)
}

// Delete mocks base method.
func (m *MockRecordsServer) Delete(arg0 context.Context, arg1 *DeleteRecordRequest) (*DeleteRecordResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*DeleteRecordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockRecordsServerMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRecordsServer)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockRecordsServer) Get(arg0 context.Context, arg1 *GetRecordRequest) (*GetRecordResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*GetRecordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRecordsServerMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRecordsServer)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockRecordsServer) List(arg0 context.Context, arg1 *ListRecordRequest) (*ListRecordResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*ListRecordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRecordsServerMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRecordsServer)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockRecordsServer) Update(arg0 context.Context, arg1 *UpdateRecordRequest) (*UpdateRecordResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*UpdateRecordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRecordsServerMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRecordsServer)(nil).Update), arg0, arg1)
}

// mustEmbedUnimplementedRecordsServer mocks base method.
func (m *MockRecordsServer) mustEmbedUnimplementedRecordsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedRecordsServer")
}

// mustEmbedUnimplementedRecordsServer indicates an expected call of mustEmbedUnimplementedRecordsServer.
func (mr *MockRecordsServerMockRecorder) mustEmbedUnimplementedRecordsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedRecordsServer", reflect.TypeOf((*MockRecordsServer)(nil).mustEmbedUnimplementedRecordsServer))
}

// MockUnsafeRecordsServer is a mock of UnsafeRecordsServer interface.
type MockUnsafeRecordsServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeRecordsServerMockRecorder
}

// MockUnsafeRecordsServerMockRecorder is the mock recorder for MockUnsafeRecordsServer.
type MockUnsafeRecordsServerMockRecorder struct {
	mock *MockUnsafeRecordsServer
}

// NewMockUnsafeRecordsServer creates a new mock instance.
func NewMockUnsafeRecordsServer(ctrl *gomock.Controller) *MockUnsafeRecordsServer {
	mock := &MockUnsafeRecordsServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeRecordsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeRecordsServer) EXPECT() *MockUnsafeRecordsServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedRecordsServer mocks base method.
func (m *MockUnsafeRecordsServer) mustEmbedUnimplementedRecordsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedRecordsServer")
}

// mustEmbedUnimplementedRecordsServer indicates an expected call of mustEmbedUnimplementedRecordsServer.
func (mr *MockUnsafeRecordsServerMockRecorder) mustEmbedUnimplementedRecordsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedRecordsServer", reflect.TypeOf((*MockUnsafeRecordsServer)(nil).mustEmbedUnimplementedRecordsServer))
}
